### ISSUE TITLE
[Feature Request] Apply tags directly to metadata

### ISSUE THREAD

**Issue by morrisoncarly97** [picobyte/stable-diffusion-webui-wd14-tagger#1]
Is there anyway this could be done ? Instead of writing the tags to a .txt files could they not be written directly to the photo metadata? Would streamline a workflow of mine quite a bit

**Comment by picobyte** [comment]
Not with the tagger, currently, but it is possible to use exiftool to write the exifdata, it should not be difficult to write a shell script that does this.
