### ISSUE TITLE
linux cant install

### ISSUE THREAD

**Issue by sdbds** [picobyte/stable-diffusion-webui-wd14-tagger#11]
For install.py, i cant start sd-webui
when i remove install.py ,it works.

**Comment by picobyte** [comment]
Hmm, I run Linux too, what does it say in the console?

**Comment by sdbds** [comment]
> Hmm, my OS is Linux too, what does it say in the console?

ok, i found it. just too slow to install requirement and it havent show
 
Install requirements for WD14-tagger

**Comment by picobyte** [comment]
ok, thanks for reporting back and closing the issue
