### ISSUE TITLE
Dependency(protobuf) conflict with other extensions

### ISSUE THREAD

**Issue by coder168** [picobyte/stable-diffusion-webui-wd14-tagger#29]
The recent [commit 64c7d0a](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/commit/64c7d0aa38aebb16e23883559f1cd86c0b9c0f6d) (tensorflow 2.10 is last supported version on native windows), tensorflow 2.10 force its dependency protobuf downgrade from 3.20.3 to 3.19.6. However, this cause version conflict of protobuf with some of other extensions (eg, [sd-webui-roop](https://github.com/s0md3v/sd-webui-roop). This cause the errors during webui starts.

**Comment by picobyte** [comment]
I've removed the version from requirements.txt it is up to the user to decide what functionality they want. I cannot resolve the different requirements that people have.

**Comment by coder168** [comment]
Hi, I did test with latest version [4e581a2](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/commit/4e581a2baeeb68b2ca6a7a7856744a78a6d43d2e). It works fine, the mentioned errors has gone. Thanks!

BTW, I checked my webui venv, the currently installed protobuf version is 4.23.4.

**Comment by picobyte** [comment]
Thanks again for reporting and reporting back. protobuf was not in requirements, it was probably implied.
