### ISSUE TITLE
API result is inconsistent with the page

### ISSUE THREAD

**Issue by v3i1r4in** [picobyte/stable-diffusion-webui-wd14-tagger#31]
1. it looks like the API response only returned tags that's excluded in the result on the web ui page.
   - I think this line is taking the wrong index from the output https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/blob/master/tagger/api.py#L99, after inspect the code, output[0] is ratting, output[1] are tags, output[2] are excluded tags, data[3] is rattings, so it's just taking ratings combining it with excluded tags.

3. I am not sure what are Excluded Tags and how their confidence value are calculated, but their confidence value in the webui does not match what's in the API response.

edit:
- after further inspection it looks like excluded value's confidence in webui is half of what's in the API output. Why are those tags's confidence halfed?

request:
- can we return all 3 in the api response? ratings, tags, excluded tags.

**Comment by picobyte** [comment]
Excluded tags are what, based on thresholds, ui params (some with defaults) is 
I think I forgot to update this. I hope this fixes it: b616adc, otherwise.. later.

**Comment by v3i1r4in** [comment]
> Excluded tags are what, based on thresholds, ui params (some with defaults) is I think I forgot to update this. I hope this fixes it: [b616adc](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/commit/b616adc4a613b3afc1984f6da6c5b609a9ee02a3), otherwise.. later.

Thank you, this is exactly what I wanted.
