### ISSUE TITLE
WD14 moat tagger v2 and WD14 ConvNeXTV2 v1 are not working

### ISSUE THREAD

**Issue by qxces** [picobyte/stable-diffusion-webui-wd14-tagger#33]
Traceback (most recent call last):
  File "D:\kal\sd\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\kal\sd\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\kal\sd\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "D:\kal\sd\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (on_interrogate) didn't receive enough output values (needed: 6, received: 3).
Wanted outputs:
    [html, html, label, label, label, html]
Received outputs:
    [None, "", "<div class='error'>Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from F:\hf\models--SmilingWolf--wd-v1-4-moat-tagger-v2\snapshots\8452cddf280b952281b6e102411c50e981cb2908\model.onnx failed:D:\a\_work\1\s\onnxruntime\core/graph/model_load_utils.h:57 onnxruntime::model_load_utils::ValidateOpsetForDomain ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 18 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain com.ms.internal.nhwc is till opset 17.
</div><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>0.8 sec.</span></p><p class='vram'><abbr title='Active: peak amount of video memory used during generation (excluding cached data)'>A</abbr>: <span class='measurement'>2.19 GB</span>, <wbr><abbr title='Reserved: total amout of video memory allocated by the Torch library '>R</abbr>: <span class='measurement'>2.20 GB</span>, <wbr><abbr title='System: peak amout of video memory allocated by all running programs, out of total capacity'>Sys</abbr>: <span class='measurement'>4.0/6 GB</span> (67.4%)</p></div>"]

**Comment by picobyte** [comment]
Does this file `F:\hf\models--SmilingWolf--wd-v1-4-moat-tagger-v2\snapshots\8452cddf280b952281b6e102411c50e981cb2908\model.onnx` exist on your system and is it ok?
