### ISSUE TITLE
This tool is difficult to use and so many bugs.

### ISSUE THREAD

**Issue by FirminSun** [picobyte/stable-diffusion-webui-wd14-tagger#34]
Issue 1: The data cache is not cleared.
Issue 2: Exclude tag: means to delete the tag which don't want.
Issue 3: Save to tag files, not working.

too hard to use.

**Comment by picobyte** [comment]
I don't seem to have issues 2 and 3. Can you describe more clearly?
Regarding issue 1, Tensorflow data cache cannot be cleared, it is inherit to tensorflow. There is an issue about it already, Toriato had the same problem, you can clear this cache by restarting the webui or converting your tensorflow models to onnx, which can be unloaded.





You can write in your own language and translate if that helps.
