### ISSUE TITLE
Gradio3.39，Display error issues，GradioDeprecationWarning

### ISSUE THREAD

**Issue by wzgrx** [picobyte/stable-diffusion-webui-wd14-tagger#42]
G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py:170: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py:386: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  gallery = gr.Gallery(

**Comment by picobyte** [comment]
resolved in f4153135d55d27977efcc80ad06ac1c785723c4f
