### ISSUE TITLE
Use multiple interrogators option? 

### ISSUE THREAD

**Issue by kuso-ge** [picobyte/stable-diffusion-webui-wd14-tagger#43]
I notice a [combine interrogations] option, but I'm not sure how it works or if it's what I'm looking for. 

I'm looking for something similar to [[Dataset Tag Editor](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor)]: 
![image](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/assets/12083007/5e27aff8-6bc7-4fe4-baaa-22637460fc35)

**Comment by picobyte** [comment]
If you enable the checkbox and you interrogate multiple times, with different interrogators, the values are combined.
