### ISSUE TITLE
Interrogator.input["cumulative"] will return True or False, But QData.clear need int param.

### ISSUE THREAD

**Issue by gamert** [picobyte/stable-diffusion-webui-wd14-tagger#48]
Also The Code Logic may be wrong for "Combine interrogations"  。While checked ,it will Clear ;While unchecked, it will Combine.  Pls Check.

  def interrogate_image(self, image: Image) -> None:
        sha = IOData.get_bytes_hash(image.tobytes())
        QData.clear(Interrogator.input["cumulative"])

**Comment by RoelKluin** [comment]
This may have to do with an old presets.json. Try removing it and write it again by saving it.

**Comment by RoelKluin** [comment]
it is not part of the repository, but if you save in the gui this stores a json file. I'll have to check at home but I thought it was called either `defaults/presets.json` in the extension root dir or `presets/defaults.json` and it may only be there after you did save in the gui.

**Comment by picobyte** [comment]
It was the latter. Can you confirm this fixed it?

**Comment by gamert** [comment]
> 

yeal, Thank you all:)
