### ISSUE TITLE
The tag "slime (substance)" apparently cannot be replaced or excluded

### ISSUE THREAD

**Issue by revolutionarycomrade** [picobyte/stable-diffusion-webui-wd14-tagger#49]
Hello, I have been unable to replace or exclude the tag "slime (substance)", unlike any other tag I have used so far which I have been able to replace or exclude without issue. Entering it in either the "Search tag" or Exclude tag" box has no effect. What might be the cause? Many thanks.

**Comment by picobyte** [comment]
The cause is probably the parentheses. The search is now a regular expression so any of these should work
`slime .substance.` `slime \(substance\)` or `slime.*` though this could match more than you want.

**Comment by revolutionarycomrade** [comment]
Great, that fixed it! Thanks for the info.
