### ISSUE TITLE
suggest：It is recommended to delete the requirements. txt and install files，Every startup will result in a large number of errors，There are still many models with face hugging links that have failed

### ISSUE THREAD

**Issue by wzgrx** [picobyte/stable-diffusion-webui-wd14-tagger#5]
*** Error running install.py for extension G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger.
*** Command: "G:\stable-diffusion-webui\venv\Scripts\Python.exe" "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\install.py"
*** Error code: 1
*** stdout: loading WD14-tagger reqs from G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt
*** Checking WD14-tagger requirements.
*** 
*** stderr: Traceback (most recent call last):
***   File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\install.py", line 11, in <module>
***     run(f'"{sys.executable}" -m pip install -r "{req_file}"',
***   File "G:\stable-diffusion-webui\modules\launch_utils.py", line 109, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install WD14-tagger requirements..
*** Command: "G:\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install -r "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt"
*** Error code: 1
*** stdout: Collecting deepdanbooru (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 1))
***   Using cached deepdanbooru-1.0.2-py3-none-any.whl (27 kB)
*** Requirement already satisfied: fastapi in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 2)) (0.94.0)
*** Requirement already satisfied: gradio in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (3.32.0)
*** Requirement already satisfied: huggingface_hub in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 4)) (0.15.1)
*** Collecting launch (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 5))
***   Using cached launch-0.1.3.tar.gz (10 kB)
***   Preparing metadata (setup.py): started
***   Preparing metadata (setup.py): finished with status 'done'
*** Collecting modules (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 6))
***   Using cached modules-1.0.0.tar.gz (525 bytes)
***   Preparing metadata (setup.py): started
***   Preparing metadata (setup.py): finished with status 'done'
*** Requirement already satisfied: numpy in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 7)) (1.23.5)
*** Requirement already satisfied: onnxruntime in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 8)) (1.15.0)
*** Requirement already satisfied: opencv_contrib_python in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 9)) (4.7.0.72)
*** Requirement already satisfied: opencv_python in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 10)) (4.7.0.72)
*** Requirement already satisfied: opencv_python_headless in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 11)) (4.7.0.72)
*** Requirement already satisfied: packaging in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 12)) (23.1)
*** Requirement already satisfied: pandas in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 13)) (2.0.2)
*** Requirement already satisfied: Pillow in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 14)) (9.5.0)
*** Requirement already satisfied: pydantic in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 15)) (1.10.8)
*** Requirement already satisfied: tensorflow in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 16)) (2.13.0)
*** Collecting tensorflow_io (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 17))
***   Using cached tensorflow_io-0.31.0-cp310-cp310-win_amd64.whl (22.9 MB)
*** Requirement already satisfied: tqdm in g:\stable-diffusion-webui\venv\lib\site-packages (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 18)) (4.65.0)
*** Collecting webui (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 19))
***   Using cached WebUI-0.1.7.zip (4.5 kB)
***   Preparing metadata (setup.py): started
***   Preparing metadata (setup.py): finished with status 'done'
*** Requirement already satisfied: Click>=7.0 in g:\stable-diffusion-webui\venv\lib\site-packages (from deepdanbooru->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 1)) (8.1.3)
*** Requirement already satisfied: scikit-image>=0.15.0 in g:\stable-diffusion-webui\venv\lib\site-packages (from deepdanbooru->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 1)) (0.20.0)
*** Requirement already satisfied: requests>=2.22.0 in g:\stable-diffusion-webui\venv\lib\site-packages (from deepdanbooru->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 1)) (2.31.0)
*** Requirement already satisfied: six>=1.13.0 in g:\stable-diffusion-webui\venv\lib\site-packages (from deepdanbooru->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 1)) (1.16.0)
*** Requirement already satisfied: starlette<0.27.0,>=0.26.0 in g:\stable-diffusion-webui\venv\lib\site-packages (from fastapi->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 2)) (0.26.1)
*** Requirement already satisfied: aiofiles in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (23.1.0)
*** Requirement already satisfied: aiohttp in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (3.8.4)
*** Requirement already satisfied: altair>=4.2.0 in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (5.0.1)
*** Requirement already satisfied: ffmpy in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (0.3.0)
*** Requirement already satisfied: gradio-client>=0.2.4 in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (0.2.7)
*** Requirement already satisfied: httpx in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (0.24.1)
*** Requirement already satisfied: jinja2 in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (3.1.2)
*** Requirement already satisfied: markdown-it-py[linkify]>=2.0.0 in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (2.2.0)
*** Requirement already satisfied: markupsafe in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (2.1.3)
*** Requirement already satisfied: matplotlib in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (3.7.1)
*** Requirement already satisfied: mdit-py-plugins<=0.3.3 in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (0.3.3)
*** Requirement already satisfied: orjson in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (3.9.0)
*** Requirement already satisfied: pydub in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (0.25.1)
*** Requirement already satisfied: pygments>=2.12.0 in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (2.15.1)
*** Requirement already satisfied: python-multipart in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (0.0.6)
*** Requirement already satisfied: pyyaml in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (6.0)
*** Requirement already satisfied: semantic-version in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (2.10.0)
*** Requirement already satisfied: typing-extensions in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (4.5.0)
*** Requirement already satisfied: uvicorn>=0.14.0 in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (0.22.0)
*** Requirement already satisfied: websockets>=10.0 in g:\stable-diffusion-webui\venv\lib\site-packages (from gradio->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 3)) (11.0.3)
*** Requirement already satisfied: filelock in g:\stable-diffusion-webui\venv\lib\site-packages (from huggingface_hub->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 4)) (3.12.0)
*** Requirement already satisfied: fsspec in g:\stable-diffusion-webui\venv\lib\site-packages (from huggingface_hub->-r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 4)) (2023.5.0)
*** INFO: pip is looking at multiple versions of launch to determine which version is compatible with other requirements. This could take a while.
*** Collecting launch (from -r G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt (line 5))
***   Using cached launch-0.1.2.tar.gz (10 kB)
***   Preparing metadata (setup.py): started
***   Preparing metadata (setup.py): finished with status 'done'
***   Using cached launch-0.1.1.tar.gz (10 kB)
***   Preparing metadata (setup.py): started
***   Preparing metadata (setup.py): finished with status 'done'
***   Using cached launch-0.1.0.tar.gz (7.2 kB)
***   Preparing metadata (setup.py): started
***   Preparing metadata (setup.py): finished with status 'done'
*** 
*** The conflict is caused by:
***     launch 0.1.3 depends on flowdas-meta<1.1 and >=1.0.1
***     launch 0.1.2 depends on flowdas-meta<1.1 and >=1.0.1
***     launch 0.1.1 depends on flowdas-meta<1.1 and >=1.0.1
***     launch 0.1.0 depends on flowdas-meta<1.1 and >=1.0.1
*** 
*** To fix this you could try to:
*** 1. loosen the range of package versions you've specified
*** 2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by wzgrx** [comment]
odel loaded in 15.8s (load weights from disk: 1.4s, create model: 1.7s, apply weights to model: 10.2s, load VAE: 1.5s, calculate empty prompt: 0.7s).
*** Error completing request
*** Arguments: (<PIL.Image.Image image mode=RGB size=1079x1920 at 0x1E807702F80>, 'Z3D-E621-Convnext') {}
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "G:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\ui.py", line 71, in on_interrogate_image
        return interrogator.interrogate_image(image)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 158, in interrogate_image
        data = ('', '', fi_key) + self.interrogate(image)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 471, in interrogate
        self.load()
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 433, in load
        model_path, tags_path = self.download()
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 383, in download
        print(f"Loading {self.name} model file from {self.kwargs['repo_id']}")
    KeyError: 'repo_id'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (on_interrogate_image) didn't receive enough output values (needed: 4, received: 3).
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Wanted outputs:
    [html, label, label, html]
Received outputs:
    [None, "", "<div class='error'>KeyError: &#x27;repo_id&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>0.0 sec.</span></p><p class='vram'><abbr title='Active: peak amount of video memory used during generation (excluding cached data)'>A</abbr>: <span class='measurement'>0.49 GB</span>, <wbr><abbr title='Reserved: total amout of video memory allocated by the Torch library '>R</abbr>: <span class='measurement'>0.53 GB</span>, <wbr><abbr title='System: peak amout of video memory allocated by all running programs, out of total capacity'>Sys</abbr>: <span class='measurement'>2.3/6 GB</span> (39.1%)</p></div>"]
*** Error completing request
*** Arguments: (<PIL.Image.Image image mode=RGB size=1079x1920 at 0x1E807702A70>, 'Z3D-E621-Convnext') {}
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "G:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\ui.py", line 71, in on_interrogate_image
        return interrogator.interrogate_image(image)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 158, in interrogate_image
        data = ('', '', fi_key) + self.interrogate(image)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 471, in interrogate
        self.load()
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 433, in load
        model_path, tags_path = self.download()
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 383, in download
        print(f"Loading {self.name} model file from {self.kwargs['repo_id']}")
    KeyError: 'repo_id'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (on_interrogate_image) didn't receive enough output values (needed: 4, received: 3).
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Wanted outputs:
    [html, label, label, html]
Received outputs:
    [None, "", "<div class='error'>KeyError: &#x27;repo_id&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>0.0 sec.</span></p><p class='vram'><abbr title='Active: peak amount of video memory used during generation (excluding cached data)'>A</abbr>: <span class='measurement'>0.49 GB</span>, <wbr><abbr title='Reserved: total amout of video memory allocated by the Torch library '>R</abbr>: <span class='measurement'>0.53 GB</span>, <wbr><abbr title='System: peak amout of video memory allocated by all running programs, out of total capacity'>Sys</abbr>: <span class='measurement'>2.3/6 GB</span> (39.1%)</p></div>"]
*** Error completing request
*** Arguments: (<PIL.Image.Image image mode=RGB size=1079x1920 at 0x1E82B1102B0>, 'Z3D-E621-Convnext') {}
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "G:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\ui.py", line 71, in on_interrogate_image
        return interrogator.interrogate_image(image)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 158, in interrogate_image
        data = ('', '', fi_key) + self.interrogate(image)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 471, in interrogate
        self.load()
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 433, in load
        model_path, tags_path = self.download()
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 383, in download
        print(f"Loading {self.name} model file from {self.kwargs['repo_id']}")
    KeyError: 'repo_id'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (on_interrogate_image) didn't receive enough output values (needed: 4, received: 3).
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Wanted outputs:
    [html, label, label, html]
Received outputs:
    [None, "", "<div class='error'>KeyError: &#x27;repo_id&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>0.0 sec.</span></p><p class='vram'><abbr title='Active: peak amount of video memory used during generation (excluding cached data)'>A</abbr>: <span class='measurement'>0.49 GB</span>, <wbr><abbr title='Reserved: total amout of video memory allocated by the Torch library '>R</abbr>: <span class='measurement'>0.53 GB</span>, <wbr><abbr title='System: peak amout of video memory allocated by all running programs, out of total capacity'>Sys</abbr>: <span class='measurement'>2.3/6 GB</span> (39.1%)</p></div>"]
Loading wd-v1-4-convnextv2-tagger-v2 model file from SmilingWolf/SW-CV-ModelZoo
*** Error completing request
*** Arguments: (<PIL.Image.Image image mode=RGB size=1079x1920 at 0x1E82B1E0100>, 'wd-v1-4-convnextv2-tagger-v2') {}
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 259, in hf_raise_for_status
        response.raise_for_status()
      File "G:\stable-diffusion-webui\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/SmilingWolf/SW-CV-ModelZoo/resolve/main/model.onnx

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "G:\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "G:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\ui.py", line 71, in on_interrogate_image
        return interrogator.interrogate_image(image)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 158, in interrogate_image
        data = ('', '', fi_key) + self.interrogate(image)
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 471, in interrogate
        self.load()
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 433, in load
        model_path, tags_path = self.download()
      File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger\interrogator.py", line 386, in download
        model_path = Path(hf_hub_download(**self.kwargs,
      File "G:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "G:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1195, in hf_hub_download
        metadata = get_hf_file_metadata(
      File "G:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "G:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1541, in get_hf_file_metadata
        hf_raise_for_status(r)
      File "G:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 291, in hf_raise_for_status
        raise RepositoryNotFoundError(message, response) from e
    huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64b288fe-71778a77610a03f4561c8a8f)

    Repository Not Found for url: https://huggingface.co/SmilingWolf/SW-CV-ModelZoo/resolve/main/model.onnx.
    Please make sure you specified the correct `repo_id` and `repo_type`.
    If you are trying to access a private or gated repo, make sure you are authenticated.
    Invalid username or password.

---
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (on_interrogate_image) didn't receive enough output values (needed: 4, received: 3).
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Wanted outputs:
    [html, label, label, html]
Received outputs:
    [None, "", "<div class='error'>RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64b288fe-71778a77610a03f4561c8a8f)

Repository Not Found for url: https://huggingface.co/SmilingWolf/SW-CV-ModelZoo/resolve/main/model.onnx.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.</div><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>0.9 sec.</span></p><p class='vram'><abbr title='Active: peak amount of video memory used during generation (excluding cached data)'>A</abbr>: <span class='measurement'>0.49 GB</span>, <wbr><abbr title='Reserved: total amout of video memory allocated by the Torch library '>R</abbr>: <span class='measurement'>0.53 GB</span>, <wbr><abbr title='System: peak amout of video memory allocated by all running programs, out of total capacity'>Sys</abbr>: <span class='measurement'>2.3/6 GB</span> (39.1%)</p></div>"]

**Comment by wzgrx** [comment]
![Snipaste_2023-07-15_20-11-58](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/assets/39661556/96928427-7746-4fa1-9460-136e660aba62)

**Comment by aearone** [comment]
Same error for me.

**Comment by picobyte** [comment]
regarding the requirements, those are what you need in the code. Removing that is just going to postpone problems.

and the repos do work for me, but then, I may have installed it manually to the right location. I will fix that.

**Comment by picobyte** [comment]
If all is well the these that were non-functional for you should no longer appear (unless you have installed them manually, like I did)

**Comment by wzgrx** [comment]
> If all is well the these that were non-functional for you should no longer appear (unless you have installed them manually, like I did)
> 
> I thinks this resolves the issue, right? thanks again.
Yes, everything is normal now
