### ISSUE TITLE
why “tagger” is not displayed in the navigation bar, but you can see the file in the plugin and settings

### ISSUE THREAD

**Issue by Aaaaniao** [picobyte/stable-diffusion-webui-wd14-tagger#50]
*** Error running install.py for extension /Users/a1/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger-master.
*** Command: "/Users/a1/stable-diffusion-webui/venv/bin/python3.10" "/Users/a1/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger-master/install.py"
*** Error code: 1
*** stdout: loading WD14-tagger reqs from /Users/a1/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger-master/requirements.txt
*** Checking WD14-tagger requirements.
*** 
*** stderr: Traceback (most recent call last):
***   File "/Users/a1/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger-master/install.py", line 11, in <module>
***     run(f'"{sys.executable}" -m pip install -q -r "{req_file}"',
***   File "/Users/a1/stable-diffusion-webui/modules/launch_utils.py", line 113, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install WD14-tagger requirements..
*** Command: "/Users/a1/stable-diffusion-webui/venv/bin/python3.10" -m pip install -q -r "/Users/a1/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger-master/requirements.txt"
*** Error code: 1
*** stderr: ERROR: Could not find a version that satisfies the requirement tensorflow_io (from versions: none)
*** ERROR: No matching distribution found for tensorflow_io

**Comment by picobyte** [comment]
I removed tensorflow_io from requirements.txt. The error seems to indicate that you cannot install it. It could be that there are more, does tensorflow also fail to install? then let me know, or if the extension now runs as normal.
