### ISSUE TITLE
Unable to use recursive search in directory

### ISSUE THREAD

**Issue by Darkenlord1** [picobyte/stable-diffusion-webui-wd14-tagger#53]
With enabled checkmark in settings - "Glob recursively with input directory pattern".

I have a folder with few folders inside it, and in them i have my images, however, tagger unable to find them.

Example of output in console:
`C:\Users\darkenlord1\Desktop\datasets\images\FFAuRa\a2\1_black: not an image extension: ""
C:\Users\darkenlord1\Desktop\datasets\images\FFAuRa\a2\1_greyscale: not an image extension: ""
C:\Users\darkenlord1\Desktop\datasets\images\FFAuRa\a2\1_red: not an image extension: ""
C:\Users\darkenlord1\Desktop\datasets\images\FFAuRa\a2\2_beige: not an image extension: ""
C:\Users\darkenlord1\Desktop\datasets\images\FFAuRa\a2\3_white: not an image extension: ""
C:\Users\darkenlord1\Desktop\datasets\images\FFAuRa\a2\8_gold: not an image extension: ""
found 0 image(s)
Tags: 0it [00:00, ?it/s]`

If i insert path to the folder where images located (not the main with all subfolders), then everything is fine.

Am i missing anything?

**Comment by picobyte** [comment]
The printing of messages for directories is redundant but not a cause of failure, however, that the glob doesn't actually find and list the files in the subdirectories was a bit surprising. I didn't change these patterns so Toriato's branch works similar. The way you had to recurse was using a glob like `/path/to/*/*`.

I changed this now, and it does recurse into subdirectories, however, if anyone queries his or her  home directory the altered behaviour might be unexpected. I'll make the recursion default false and place the checkbox back on the tagger tab, not settings.
