### ISSUE TITLE
Startup spends 3 extra seconds on installer

### ISSUE THREAD

**Issue by catboxanon** [picobyte/stable-diffusion-webui-wd14-tagger#56]
![image](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/assets/122327233/74339363-2d43-4293-9c06-f63bca76558f)

This seems to be the only extension I have with this behavior. Ideally this shouldn't need to execute on every startup. A temporary workaround could be to honor the `--skip-install` argument, [which is used in the built-in `run_pip` function](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/72ee347eabf04d1a238a738a03e7973cc2a46ca3/modules/launch_utils.py#L133-L135) (this is normally what is used within the `install.py` scripts for extensions).

**Comment by picobyte** [comment]
feel free to send a PR

**Comment by picobyte** [comment]
Thanks!
