### ISSUE TITLE
It always shows loading.它一直显示加载中

### ISSUE THREAD

**Issue by BasicGearwheel** [picobyte/stable-diffusion-webui-wd14-tagger#57]
Just like this.After I put my image into the box, it started loading and never ended the process.However, it never outputs anything
就像这样，当我把我的图片放进去后，它开始加载模型但是一直没有停止。总而言之，不输出任何东西。
![IMG_20230828_172510](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/assets/61679493/7657641d-05f1-4e77-b2aa-77e7b718e3bb)

![IMG_20230828_191620](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/assets/61679493/478309ec-90ef-4d5a-a7c3-f253d74050d6)

**Comment by BasicGearwheel** [comment]
Windows的任务管理器也没有显示WebUI有任何负载（不占用任何CPU/GPU资源）。
Windows Task Manager showed that WebUI had nothing to do.(Does not occupy any CPU/GPU resources)

**Comment by picobyte** [comment]
What is the error, it keeps loading? You have a local install and have no connection? There is another issue about that.

**Comment by BasicGearwheel** [comment]
> What is the error, it keeps loading? I don't have this issue. Do you have a local install and no connection? There is another issue that indicates how a local model can be loaded, I cannot read Chinese, but in case it helps, it is here:#26 .
> 
> 这是什么错误，一直在加载？我的没有这个问题您是否有本地安装且没有连接？还有另一个问题表明如何加载本地模型，我看不懂中文，但如果它有帮助，它在这里：#26。

I have completed the necessary steps.However, when I use other‘s WebUI pack(Qiuye from China) , it was like the situation previous situation.Maybe graphics card I use is special.The GPU is P104-100 and the  NVIDIA driver version is 537.13.But the computer's video output graphics card is AMD's RX 580 8G.

**Comment by BasicGearwheel** [comment]
> iver version is 537.13.But the computer's video output graphics card is AMD's RX 580 8G.

![SharedScreenshot](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/assets/61679493/ef63e439-d5d3-486c-ad9c-69e4e97a5a71)

**Comment by picobyte** [comment]
Does the wd14 tagger and interrogation work if you run Automatic1111 webui with `--use-cpu all`? If you check this you can confirm that it could be the video card settings.
如果您使用“--use-cpu all”运行Automatic1111 webui，wd14标记器和询问是否可以工作？如果您检查此项，则可以确认这可能是视频卡设置的问题。

**Comment by BasicGearwheel** [comment]
> Does the wd14 tagger and interrogation work if you run Automatic1111 webui with `--use-cpu all`? If you check this you can confirm that it could be the video card settings. 如果您使用“--use-cpu all”运行Automatic1111 webui，wd14标记器和询问是否可以工作？如果您检查此项，则可以确认这可能是视频卡设置的问题。

Yes.After I use the CPU to run WebUI , it's successful to get the tags.

**Comment by BasicGearwheel** [comment]
> Does the wd14 tagger and interrogation work if you run Automatic1111 webui with `--use-cpu all`? If you check this you can confirm that it could be the video card settings. 如果您使用“--use-cpu all”运行Automatic1111 webui，wd14标记器和询问是否可以工作？如果您检查此项，则可以确认这可能是视频卡设置的问题。
> 
> There may be a few more options relevant. I use these: 可能还有其他一些相关选项。我用这些：
> 
> ```
![SharedScreenshot](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/assets/61679493/8b8358c4-fa6e-4520-9d61-06a4dfee052f)

> HSA_OVERRIDE_GFX_VERSION=10.3.0 \
> COMMANDLINE_ARGS="--skip-torch-cuda-test --precision full --use-cpu all --api --no-half --disable-nan-check --theme=dark" ./webui.sh
> ```

It also works fine when I use a privately modified Nvidia graphics driver.

**Comment by BasicGearwheel** [comment]
> Does the wd14 tagger and interrogation work if you run Automatic1111 webui with `--use-cpu all`? If you check this you can confirm that it could be the video card settings. 如果您使用“--use-cpu all”运行Automatic1111 webui，wd14标记器和询问是否可以工作？如果您检查此项，则可以确认这可能是视频卡设置的问题。
> 
> There may be a few more options relevant. I use these: 可能还有其他一些相关选项。我用这些：
> 
> ```
> HSA_OVERRIDE_GFX_VERSION=10.3.0 \
> COMMANDLINE_ARGS="--skip-torch-cuda-test --precision full --use-cpu all --api --no-half --disable-nan-check --theme=dark" ./webui.sh
> ```

However, privately modified graphics card drivers sometimes cannot fully keep up with the update speed of the official driver (I just used the official driver), which results in us sometimes not being able to use the latest official driver to improve the WebUI experience. Even if we can keep the plug-in running normally by changing the parameters to start the WebUI, it is a very troublesome thing. There may be many SD players in China who use this type of graphics card (CMP p106, p104, p102, 30hx, 40hx...). I hope developer can add a convenient "Run on CPU"  button to use convniently.

**Comment by picobyte** [comment]
In preload.py I had previously added one option, can you try with `--additional-device-ids cpu:0`, let me know if that works for you
在 preload.py 中，我之前添加了一个选项，您可以尝试使用 `--additional-device-ids cpu:0`，让我知道这是否适合您

**Comment by BasicGearwheel** [comment]
> In preload.py I had previously added one option, can you try with `--additional-device-ids cpu:0`, let me know if that works for you 在 preload.py 中，我之前添加了一个选项，您可以尝试使用 `--additional-device-ids cpu:0`，让我知道这是否适合您

![SharedScreenshot](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/assets/61679493/f1b477ac-dcd1-497b-b3e4-c2cc0e636dc9)

Now , no problem .Thank you!

**Comment by picobyte** [comment]
Good to hear. by the way,f you (or someone else) has a second gpu `--additional-device-ids gpu:1` should work as well
很高兴听到。顺便说一句，如果您（或其他人）有第二个 GPU `--additional-device-ids gpu:1` 也应该可以工作
