### ISSUE TITLE
How to get this extension working with Stable Diffusion  v1.6.0? 

### ISSUE THREAD

**Issue by tomkuo1124** [picobyte/stable-diffusion-webui-wd14-tagger#62]
Hello,

Can anyone help me to get this extension working with Stable Diffusion  v1.6.0?
It seems to install but it won't show up on the UI.
I also found the latest release on "Stablizing" on Releases topic, may I know if the version work on Stable Diffusion  v1.6.0?
Or please kindly guide if anyway can use the tagger?
The build in prompt generate tools "Interrogate CLIP, Interrogate DeepBooru" suck and can't generate proper picture.
It would be appreciate if anyone can help me. 😓
Thanks a lot.

**Comment by RoelKluin** [comment]
If an extension does not show up, there's an error displayed on the console, usually, indicating the cause. It should mention something with the wd14 tagger path, Can you post that?

**Comment by tomkuo1124** [comment]
hi sir,
Appreciate for your feedback, please kindly refer my uploaded video and screenshots.
Thanks.

![2023-09-08 17 30 08](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/assets/137477635/f3f7f555-653e-4be0-b313-53e1bf9b

https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/assets/137477635/2e069ac3-721e-4346-9f70-2e5fbb10ad85

1244)

**Comment by tomkuo1124** [comment]
Here is the screenshot.
![2023-09-08 17 30 08](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/assets/137477635/6acd8ab2-5165-4eb2-9c9b-a34966a7234b)

**Comment by tomkuo1124** [comment]
I found my error may relate with this article:
https://github.com/google-research/torchsde/issues/131

The package torchsde version 0.2.5 has a non-standard dependency specifier for numpy. This will be enforced in pip 23.3.
I am use Windows 11 system, please kindly guild me the steps to trouble shoot this issue.
Thanks a lot.

**Comment by tomkuo1124** [comment]
Sorry, I found solution on below website:
https://github.com/google-research/torchsde/issues/131

This issue will be closed.

**Comment by RoelKluin** [comment]
No problem, glad you resolved it.
