### ISSUE TITLE
Exclude Character Name

### ISSUE THREAD

**Issue by tkgix** [picobyte/stable-diffusion-webui-wd14-tagger#63]
Thank you for your efforts.

I'd like to suggest the function to exclude character names from tags.

This function is implemented through a checkbox to exclude tags corresponding ( Maybe category 4 )

**Comment by RoelKluin** [comment]
Relevant may be issue #13. There is a fork of Toriato's original branch, mentioned there, which handles character tags. This branch is not yet merged in this branch. If that branch works well, maybe mention it here.

**Comment by picobyte** [comment]
Characters are prepended with 'character:', right? So can't this be done with an exclude regexp?
