### ISSUE TITLE
Excudes Tags do not works？

### ISSUE THREAD

**Issue by RedDestiny** [picobyte/stable-diffusion-webui-wd14-tagger#65]
I update to the newest version，and add “censored,mosaic_censoring,blur_censor,monochrome,uncensored,” to Settings tab->Tagger->Excudes (split by comma). But it do not  works.
It is a bug?

设置里的排除tag的功能没有用的样子，是BUG吗？

**Comment by picobyte** [comment]
Is it the stray comma?
Otherwise, what exactly is the bug, everything filtered or nothing filtered?

**Comment by RedDestiny** [comment]
Settings tab->Tagger->Excudes do not works whith any tags，but “excludes tag - bottom right - on the tagger tab” works well.I think it is a bug.

**Comment by picobyte** [comment]
If it is just for a different purpose than you assumed, then it is not a bug.
