### ISSUE TITLE
If it possible to install model by ourselves without huggingface downloading?

### ISSUE THREAD

**Issue by BasicGearwheel** [picobyte/stable-diffusion-webui-wd14-tagger#70]
It seems that developer have updated the tagger before.Can I download the model and install it in SD by myself now?

**Comment by RoelKluin** [comment]
There is a PR that is being worked on to handle this. The huggingface download can be prevented with environment variables. There are also two left open issues that describe a possible resolution: #26 and #46, I don't think we need another.
