### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by lsycxyj** [picobyte/stable-diffusion-webui-wd14-tagger#80]
Is there a way to cleanup the VRAM occupied by this extension? Or could you compute the tags in a subprocess and kill it to release the VRAM after the computation?

**Comment by RoelKluin** [comment]
It is not this extension, see #17

**Comment by lsycxyj** [comment]
@RoelKluin I know it's the problem related to tensorflow. However, is there a way that I can release the VRAM? I can't see the  solution or workaround for this extension in #17.

**Comment by RoelKluin** [comment]
Not really. You can convert the model to onnx as WSH032 mentions there, otherwise restart the webui or avoid the tensorflow models.
